### ISSUE TITLE
Broken Colab URL on PyPI page for v1.0

### ISSUE THREAD

**Issue by bugbounted** [dhyeythumar/gym-video-streamer#1]
Hi [Dhyey Thumar](https://github.com/dhyeythumar),
after visiting colab link embed in pypi page , error me file not found :
https://github.com/dhyeythumar/gym-video-streamer/blob/main/Streaming-Gym-Envs-from-Colab.ipynb
please re upload to main branch
finest regards

**Comment by dhyeythumar** [comment]
Hi @elmirarokni,
I was not aware of this URL issue. Thanks for reporting it.

For now you can use this (colab URL is correct in this repo's v1.0 branch) - https://colab.research.google.com/github/dhyeythumar/gym-video-streamer/blob/v1.0/Streaming%20Gym%20Envs%20from%20Colab%20-v1.0.ipynb

To fix the link on pypi page it would require me to upload new version of the project, & that to without having any code changes. So I need to think how to avoid new release for this change.

**Comment by dhyeythumar** [comment]
@elmirarokni I hope the missing URL issue is solved. I will update here once the URL issue is fixed on pypi. For now closing this issue but will keep this issue pinned.
